language: rust

rust:
  - stable
  - nightly

matrix:
  allow_failures:
    - rust: stable
  fast_finish: true

cache:
  - apt
  - cargo

script:
  - cargo build --verbose
  # - cargo test --verbose

before_deploy:
  - cargo doc
  # - mdbook build book
  - mkdir public
  - cp -r target/doc public/
  # - cp -r target/book public/
  - pwd
  - ls
  - echo "<meta http-equiv=refresh content=0;url=book/html/index.html>" > public/index.html

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: public
  on:
    branch: master
