[global.databases]
pg_db = { url = "postgres://goto:gotopassword@192.168.20.102/goto", pool_size = 8 }

[development]
address = "0.0.0.0"
port = 80
workers = 4
keep_alive = 5
log = "normal"
# secret_key = [randomly generated at launch]
limits = { forms = 32768 }

[production]
address = "0.0.0.0"
port = 80
workers = 4
keep_alive = 5
log = "critical"
# secret_key = [randomly generated at launch]
limits = { forms = 32768 }
